const stickers=[
['hello-day','こんにちは！','HELLO','greeting'],['im-home','ただいま！','I’M HOME','greeting'],['see-you','またね！','SEE YOU','greeting'],['hello','よろしく！','LET’S GO','greeting'],
['ok','OK！','ALL GOOD','reply'],['understood','了解です！','GOT IT','reply'],['wait','ちょっと待って！','WAIT A SEC','reply'],
['thanks','ありがとう！','THANK YOU','feeling'],['love','すき','LOVE IT','feeling'],['seriously','まじか','SERIOUSLY?','feeling'],['cry','泣','CRYING','feeling'],['lonely','しょんぼり…','FEELING BLUE','feeling'],
['good-job','おつかれさま！','GOOD JOB','cheer'],['congrats','おめでとう！','CONGRATS','cheer'],['yay','やったー！','YAY','cheer'],['going','いってきます！','I’M OFF','cheer']
].map(([id,name,sub,category])=>({id,name,sub,category,file:`stamps/${id}.png`}));
const grid=document.querySelector('#grid'),empty=document.querySelector('#empty'),modal=document.querySelector('#modal'),preview=document.querySelector('#preview'),favOnly=document.querySelector('#favOnly');let active,showFavs=false,category='all',favorites=new Set(JSON.parse(localStorage.getItem('kanon-favorites')||'[]'));
function render(){grid.replaceChildren();let list=category==='all'?stickers:stickers.filter(s=>s.category===category);if(showFavs)list=list.filter(s=>favorites.has(s.id));empty.hidden=!!list.length;grid.hidden=!list.length;document.querySelector('#emptyTitle').textContent=showFavs?'この種類のお気に入りはまだありません':'スタンプがありません';document.querySelector('#emptyText').textContent=showFavs?'ハートを押すと、ここに集められます。':'別の種類を選んでみてください。';list.forEach(s=>{const el=document.createElement('article');el.className='stamp';el.innerHTML=`<button class="stamp-open" aria-label="${s.name}を開く"><span class="visual"><img src="${s.file}" alt="${s.name}" loading="lazy"></span><b>${s.name}</b><small>${s.sub}</small></button><span class="tap">TAP TO USE</span><button class="heart ${favorites.has(s.id)?'on':''}" aria-label="お気に入り">${favorites.has(s.id)?'♥':'♡'}</button>`;el.querySelector('.stamp-open').onclick=()=>open(s);el.querySelector('.heart').onclick=()=>toggle(s.id);grid.append(el)})}
function toggle(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('kanon-favorites',JSON.stringify([...favorites]));render()}function open(s){active=s;preview.src=s.file;preview.alt=s.name;document.querySelector('#selected').textContent=s.name;modal.hidden=false;document.body.style.overflow='hidden'}function close(){modal.hidden=true;document.body.style.overflow=''}async function blob(){return (await fetch(active.file)).blob()}const say=t=>{const e=document.querySelector('#notice');e.textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>e.textContent='',3200)};
document.querySelector('#close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()});document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.write([new ClipboardItem({'image/png':await blob()})]);say('コピーしました！LINEに貼り付けてね。')}catch{say('コピーできない場合は「送る」か「保存」を使ってね。')}};document.querySelector('#share').onclick=async()=>{const f=new File([await blob()],`${active.id}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:active.name});else document.querySelector('#save').click()}catch(e){if(e.name!=='AbortError')say('保存してから送ってね。')}};document.querySelector('#save').onclick=async()=>{const a=document.createElement('a');a.href=URL.createObjectURL(await blob());a.download=`kanon-${active.id}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);say('PNGを保存しました！')};favOnly.onclick=()=>{showFavs=!showFavs;favOnly.setAttribute('aria-pressed',showFavs);favOnly.textContent=showFavs?'♥':'♡';render()};document.querySelectorAll('#categories button').forEach(button=>button.onclick=()=>{document.querySelectorAll('#categories button').forEach(x=>x.classList.remove('on'));button.classList.add('on');category=button.dataset.category;render()});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
